name: Test Homework 07

on: 
  push:
    paths:
      Homework/07/scripts/*.py

jobs:
  test-lora:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Homework/07/requirements.txt
    - name: Download test
      run: |
        wget https://raw.githubusercontent.com/makarenko95/llm-course-2024-autumn/refs/heads/main/Homework/07/tests/test_lora.py -O Homework/07/tests/test_lora.py
    - name: Run unit test
      run: |
        cd Homework/07/
        python -m unittest -v tests/test_lora.py
  test-quantization:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Homework/07/requirements.txt
    - name: Download test
      run: |
        wget https://raw.githubusercontent.com/makarenko95/llm-course-2024-autumn/refs/heads/main/Homework/07/tests/test_quantization.py -O Homework/07/tests/test_quantization.py
    - name: Run unit test
      run: |
        cd Homework/07/
        python -m unittest -v tests/test_quantization.py
