name: Test Homework 04

on: 
  workflow_dispatch:

jobs:
  test-minhash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: Homework/04/requirements.txt
    - name: Test MinHash
      run: python -m pip install --upgrade pip && pip install -r Homework/04/requirements.txt && python -m unittest -v Homework/04/tests/test_minhash.py
  test-minhashlsh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: Homework/04/requirements.txt
    - name: Test MinHashLSH
      run: python -m pip install --upgrade pip && pip install -r Homework/04/requirements.txt && python -m unittest -v Homework/04/tests/test_minhashlsh.py
