name: Test Homework 03

on:
  workflow_dispatch:

jobs:
  test-tokenizer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Homework/03/requirements.txt
    - name: Test ALiBI
      run: python -m pytest -s Homework/03/tests/test_alibi.py
    - name: Test GQA
      run: python -m pytest -s Homework/03/tests/test_gqa.py
